services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: public
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
