-- 1.
CREATE TABLE PESSOA (
    CPF VARCHAR(8) NOT NULL,
    NOME VARCHAR(60) PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO DATE,

    CONSTRAINT PK_CPF PRIMARY KEY (CPF),
    CONSTRAINT UN_EMAIL UNIQUE (EMAIL)
)

-- 2.
CREATE TABLE INTERNO(
    NUSP VARCHAR(8) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    
    CONSTRAINT FK_INTERNO_PESSOA FOREIGN KEY (CPF)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE
            ON UPDATE CASCADE
    CONSTRAINT UN_INTERNO UNIQUE (CPF)
)

-- 3.
CREATE TABLE FUNCIONARIO(
    NUSP VARCHAR(8) NOT NULL,
    FORMACAO VARCHAR(20),

    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (NUSP),
    CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (NUSP)
        REFERENCES INTERNO (NUSP)
            ON DELETE CASCADE 
            ON UPDATE CASCADE
)

-- 4.
CREATE TABLE RESTRICOES_FISICAS (
    NUSP VARCHAR(8) NOT NULL,
    RESTRICOES VARCHAR(30) NOT NULL,

    CONSTRAINT PK_RESTRICOES_FISICAS PRIMARY KEY (NUSP, RESTRICOES),
    CONSTRAINT FK_RESTRICOES_FISICAS FOREIGN KEY (NUSP),
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 5.
CREATE TABLE EDUCADOR_FISICO (
    NUMERO_CONSELHO VARCHAR(13) NOT NULL,
    NUSP VARCHAR(8) NOT NULL,
    
    CONSTRAINT PK_EDUCADOR_FISICO PRIMARY KEY (NUMERO_CONSELHO),
    CONSTRAINT FK_EDUCADOR_FISICO UNIQUE (NUSP),
    CONSTRAINT FK_EDUCADOR_FISICO FOREIGN KEY (NUSP)
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 6.
CREATE TABLE ESPACO (
    BLOCO VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(3) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    EH_RESERVAVEL VARCHAR(5) NOT NULL,

    CONSTRAINT PK_ESPACO PRIMARY KEY (BLOCO, NUMERO)
)

-- 9.
CREATE TABLE EQUIPAMENTO(
    ID_PATRIMONIAL IDENTITY(1,1),
    BLOCO_ESPACO VARCHAR(2) NOT NULL,
    NUMERO_ESPACO VARCHAR(3) NOT NULL,
    PRECO VARCHAR (10),
    DATA_AQUISICAO DATE NOT NULL,

    CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (ID_PATRIMONIAL),
    CONSTRAINT FK_EQUIPAMENTOESPACO FOREIGN KEY (BLOCO_ESPACO, NUMERO_ESPACO)
        REFERENCES ESPACO (BLOCO, NUMERO)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 10.
CREATE TABLE DOACAO(
    ID_DOACAO IDENTITY(1,1) PRIMARY KEY,
    CPF_DOADOR VARCHAR(8),

    CONSTRAINT FK_DOACAO FOREIGN KEY (ID_DOACAO)
        REFERENCES EQUIPAMENTO (ID_PATRIMONIAL)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DOADOR FOREIGN KEY (CPF_DOADOR)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 11.
CREATE TABLE RESERVA_INSTALACAO (
    NUSP VARCHAR(8) NOT NULL,
    ID_INSTALACAO IDENTITY(1,1),
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,

    CONSTRAINT PK_RESERVA_INSTALACAO PRIMARY KEY (ID_INSTALACAO),
    CONSTRAINT FK_RESERVA_INSTALACAO KEY (ID_INSTALACAO)
        REFERENCES INSTALACAO_RESERVAVEL (ID_INSTALACAO),
    CONSTRAINT FK_RESERVA_INSTALACAO FOREIGN KEY (NUSP)
        REFERENCES EDUCADOR_FISICO (NUSP),
)

-- 12.
CREATE TABLE RESERVA_EQUIPAMENTO (
    NUSP VARCHAR(8) NOT NULL,
    ID_PATRIMONIAL IDENTITY(1,1) PRIMARY KEY,
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,
    DEVOLVIDO? VARCHAR(5) NOT NULL,

    CONSTRAINT PK_RESERVA_EQUIPAMENTO PRIMARY KEY (ID_PATRIMONIAL),
    CONSTRAINT FK_RESERVA_EQUIPAMENTO FOREIGN KEY (ID_PATRIMONIAL)
        REFERENCES EQUIPAMENTO (ID_PATRIMONIAL),
    CONSTRAINT FK_RESERVA_EQUIPAMENTO FOREIGN KEY (NUSP)
        REFERENCES EDUCADOR_FISICO (NUSP)
)

-- 13.
CREATE TABLE GRUPO_DE_EXTENSAO (
    NOME VARCHAR(40),
    DESCRICAO VARCHAR(60),
    RESPONSAVELNUSP VARCHAR(8) NOT NULL,

    CONSTRAINT PK_GRUPO_DE_EXTENSAO PRIMARY KEY (NOME),
    CONSTRAINT FK_GRUPO_DE_EXTENSAO FOREIGN KEY (RESPONSAVELNUSP)
        REFERENCES EDUCADOR_FISICO (NUSP),
)

-- 14.
CREATE TABLE ATRIBUICOES (
    NUSP VARCHAR(8) NOT NULL,
    ATRIBUICAO VARCHAR(20) NOT NULL,
    
    CONSTRAINT PK_ATRIBUICOES PRIMARY KEY (NUSP, ATRIBUICAO),
    CONSTRAINT FK_ATRIBUICOES FOREIGN KEY (NUSP)
        REFERENCES FUNCIONARIO (NUSP)
)

-- 15.
CREATE TABLE EVENTO (
    ID_EVENTO IDENTITY(1,1) NOT NULL,
    NUSP_RESPONSAVEL VARCHAR(8) NOT NULL,
    ID_INSTALACAO IDENTITY(1,1) PRIMARY KEY,
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,
    DESCRICAO VARCHAR(60),
    EDUCADOR_FISICO VARCHAR(8) NOT NULL,
    NOME_EVENTO VARCHAR(40) NOT NULL,
    EDUCADOR_FISICO VARCHAR(8) NOT NULL,

    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EVENTO_INSTALACAO FOREIGN KEY (NUSP_RESPONSAVEL)
)