CREATE TABLE PESSOA (
    CPF VARCHAR(8) NOT NULL
    NOME VARCHAR(60) PRIMARY KEY
    EMAIL VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO DATE
    UNIQUE EMAILPESSOA (EMAIL)
)

CREATE TABLE INTERNO(
    NUSP VARCHAR(8) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    FOREIGN KEY CPFINTERNO (CPF)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE CPFINTERNO (CPF)
)

CREATE TABLE FUNCIONARIO(
    NUSP VARCHAR(8) PRIMARY KEY,
    FORMACAO VARCHAR(20),
    FOREIGN KEY NUSPFUNCIONARIO (NUSP)
        REFERENCES INTERNO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE RESTRICOES_FISICAS (
    NUSP VARCHAR(8),
    RESTRICOES VARCHAR(30),
    PRIMARY KEY NUSPRESTRICOES (NUSP, RESTRICOES),
    FOREIGN KEY NUSPFUNCIONARIO (NUSP)
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE EDUCADOR FISICO (
    NUMERO_CONSELHO VARCHAR(13) PRIMARY KEY,
    NUSP VARCHAR(8),
    FOREIGN KEY NUSPEDUCADOR (NUSP)
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE FUNCIONARIO (NUSP)
)

CREATE TABLE ESPACO (
    BLOCO VARCHAR(2),
    NUMERO VARCHAR(3),
    NOME VARCHAR(20) NOT NULL,
    PRIMARY KEY BLOCONUMERO (BLOCO, NUMERO)
)

CREATE TABLE INSTALACAO_RESERVAVEL(
    BLOCO_ESPACO VARCHAR(2),
    NUMERO_ESPACO VARCHAR(3),
    NOME VARCHAR(20) NOT NULL,
    
    PRIMARY KEY ESPACO (BLOCO_ESPACO, NUMERO_ESPACO)
    FOREIGN KEY INSTALACAOESPACO (BLOCO_ESPACO, NUMERO_ESPACO)
        REFERENCES ESPACO (BLOCO, NUMERO)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE INSTALACAO_NAO_RESERVAVEL(
    BLOCO_ESPACO VARCHAR(2),
    NUMERO_ESPACO VARCHAR(3),
    NOME VARCHAR(20) NOT NULL,
    
    PRIMARY KEY ESPACO (BLOCO_ESPACO, NUMERO_ESPACO)
    FOREIGN KEY INSTALACAOESPACO (BLOCO_ESPACO, NUMERO_ESPACO)
        REFERENCES ESPACO (BLOCO, NUMERO)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE EQUIPAMENTO(
    ID_PATRIMONIAL IDENTITY(1,1) PRIMARY KEY,
    BLOCO_ESPACO VARCHAR(2) NOT NULL,
    NUMERO_ESPACO VARCHAR(3) NOT NULL,
    PRECO VARCHAR (10),
    DATA_AQUISICAO DATE NOT NULL,

    FOREIGN KEY EQUIPAMENTOESPACO (BLOCO_ESPACO, NUMERO_ESPACO)
        REFERENCES ESPACO (BLOCO, NUMERO)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE DOACAO(
    ID_DOACAO IDENTITY(1,1) PRIMARY KEY,
    CPF_DOADOR VARCHAR(8),

    FOREIGN KEY DOACAO (ID_DOACAO)
        REFERENCES EQUIPAMENTO (ID_PATRIMONIAL)
            ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY DOADOR (CPF_DOADOR)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

