-- 1.
CREATE TABLE PESSOA (
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(60) PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO DATE,

    CONSTRAINT PK_CPF PRIMARY KEY (CPF),
    CONSTRAINT UN_EMAIL UNIQUE (EMAIL)
)

-- 2.
CREATE TABLE INTERNO(
    CPF VARCHAR(11) NOT NULL,
    NUSP VARCHAR(8) NOT NULL,
    
    CONSTRAINT PK_INTERNO PRIMARY KEY (CPF),
    CONSTRAINT FK_INTERNO_PESSOA FOREIGN KEY (CPF)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE
            ON UPDATE CASCADE
    CONSTRAINT UN_INTERNO UNIQUE (NUSP)
)

-- 3.
CREATE TABLE FUNCIONARIO(
    NUSP VARCHAR(8) NOT NULL,
    FORMACAO VARCHAR(20),

    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (NUSP),
    CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (NUSP)
        REFERENCES INTERNO (NUSP)
            ON DELETE CASCADE 
            ON UPDATE CASCADE
)

-- 4.
CREATE TABLE FUNCIONARIO_RESTRICOES (
    NUSP_FUNCIONARIO VARCHAR(8) NOT NULL,
    RESTRICOES_FISICAS VARCHAR(30) NOT NULL,

    CONSTRAINT PK_FUNCIONARIO_RESTRICOES PRIMARY KEY (NUSP_FUNCIONARIO, RESTRICOES),
    CONSTRAINT FK_FUNCIONARIO_RESTRICOES FOREIGN KEY (NUSP_FUNCIONARIO),
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 5.
CREATE TABLE FUNCIONARIO_ATRIBUICAO (
    NUSP_FUNCIONARIO VARCHAR(8) NOT NULL,
    ATRIBUICAO VARCHAR(20) NOT NULL,
    
    CONSTRAINT PK_FUNCIONARIO_ATRIBUICAO PRIMARY KEY (NUSP_FUNCIONARIO, ATRIBUICAO),
    CONSTRAINT FK_FUNCIONARIO_ATRIBUICAO FOREIGN KEY (NUSP_FUNCIONARIO)
        REFERENCES FUNCIONARIO (NUSP)
)

-- 6.
CREATE TABLE EDUCADOR_FISICO (
    NUMERO_CONSELHO VARCHAR(13) NOT NULL,
    NUSP VARCHAR(8) NOT NULL,
    
    CONSTRAINT PK_EDUCADOR_FISICO PRIMARY KEY (NUMERO_CONSELHO),
    CONSTRAINT FK_EDUCADOR_FISICO UNIQUE (NUSP),
    CONSTRAINT FK_EDUCADOR_FISICO FOREIGN KEY (NUSP)
        REFERENCES FUNCIONARIO (NUSP)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 6.
CREATE TABLE ESPACO (
    BLOCO VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(3) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    EH_RESERVAVEL VARCHAR(5) NOT NULL,

    CONSTRAINT PK_ESPACO PRIMARY KEY (BLOCO, NUMERO)
    CONSTRAINT EH_RESERVAVEL CHECK (EH_RESERVAVEL IN ('SIM', 'NAO')
)

-- 7.
CREATE TABLE EQUIPAMENTO(
    ID_PATRIMONIAL IDENTITY(1,1),
    BLOCO_ESPACO VARCHAR(2) NOT NULL,
    NUMERO_ESPACO VARCHAR(3) NOT NULL,
    PRECO VARCHAR (10),
    DATA_AQUISICAO DATE NOT NULL,

    CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (ID_PATRIMONIAL),
    CONSTRAINT FK_EQUIPAMENTOESPACO FOREIGN KEY (BLOCO_ESPACO, NUMERO_ESPACO)
        REFERENCES ESPACO (BLOCO, NUMERO)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 8.
CREATE TABLE DOACAO(
    ID_DOACAO IDENTITY(1,1),
    CPF_DOADOR VARCHAR(8),
    DATA DATE NOT NULL,

    CONSTRAINT PK_DOACAO PRIMARY KEY (ID_DOACAO),
    CONSTRAINT FK_DOACAO FOREIGN KEY (ID_DOACAO)
        REFERENCES EQUIPAMENTO (ID_PATRIMONIAL)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DOADOR FOREIGN KEY (CPF_DOADOR)
        REFERENCES PESSOA (CPF)
            ON DELETE CASCADE ON UPDATE CASCADE,
)

-- 9.
CREATE TABLE RESERVA_ESPACO(
    NUSP VARCHAR(8) NOT NULL,
    BLOCO VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(3) NOT NULL,
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,

    CONSTRAINT PK_RESERVA_ESPACO PRIMARY KEY (NUSP, BLOCO, NUMERO, DATA, HORARIO_INICIO),
    CONSTRAINT FK_RESERVA_ESPACO KEY (BLOCO, NUMERO)
        REFERENCES ESPACO (BLOCO, NUMERO),
    CONSTRAINT FK_RESERVA_ESPACO FOREIGN KEY (NUSP)
        REFERENCES INTERNO (NUSP),
)

-- 10.
CREATE TABLE RESERVA_EQUIPAMENTO (
    NUSP VARCHAR(8) NOT NULL,
    ID_PATRIMONIAL IDENTITY(1,1) PRIMARY KEY,
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,
    DEVOLVIDO? VARCHAR(5) NOT NULL,

    CONSTRAINT PK_RESERVA_EQUIPAMENTO PRIMARY KEY (ID_PATRIMONIAL),
    CONSTRAINT FK_RESERVA_EQUIPAMENTO FOREIGN KEY (ID_PATRIMONIAL)
        REFERENCES EQUIPAMENTO (ID_PATRIMONIAL),
    CONSTRAINT FK_RESERVA_EQUIPAMENTO FOREIGN KEY (NUSP)
        REFERENCES EDUCADOR_FISICO (NUSP)
)

-- 11.
CREATE TABLE GRUPO_DE_EXTENSAO (
    NOME VARCHAR(40),
    DESCRICAO VARCHAR(60),
    RESPONSAVELNUSP VARCHAR(8) NOT NULL,

    CONSTRAINT PK_GRUPO_DE_EXTENSAO PRIMARY KEY (NOME),
    CONSTRAINT FK_GRUPO_DE_EXTENSAO FOREIGN KEY (RESPONSAVELNUSP)
        REFERENCES EDUCADOR_FISICO (NUSP),
)

-- 13.
CREATE TABLE EVENTO (
    ID_EVENTO IDENTITY(1,1) NOT NULL,
    NUSP_RESPONSAVEL VARCHAR(8) NOT NULL,
    ID_INSTALACAO IDENTITY(1,1) PRIMARY KEY,
    DATA DATE NOT NULL,
    HORARIO_INICIO VARCHAR(8) NOT NULL,
    HORARIO_FIM VARCHAR(8) NOT NULL,
    DESCRICAO VARCHAR(60),
    EDUCADOR_FISICO VARCHAR(8) NOT NULL,
    NOME_EVENTO VARCHAR(40) NOT NULL,
    EDUCADOR_FISICO VARCHAR(8) NOT NULL,

    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EVENTO_INSTALACAO FOREIGN KEY (NUSP_RESPONSAVEL)
)